repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,markdown']
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
        args: ['--fix=lf']
